const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
const uid = () => Math.random().toString(36).slice(2, 10);
const localISO = (date = new Date()) => { const d = new Date(date.getTime() - date.getTimezoneOffset()*60000); return d.toISOString().slice(0,10); };
const todayISO = () => localISO();
const money = n => '£' + Number(n||0).toLocaleString('en-GB',{maximumFractionDigits:2});
const storeKey = 'commandCentrePersonalOS.v5.ridiculous';
const migrateKeys = ['commandCentrePersonalOS.v2','commandCentrePersonalOS.v1'];
const teamColours = ['#f97316','#22c55e','#38bdf8','#a78bfa','#f43f5e','#eab308','#14b8a6'];
const defaultTeam = [{id:'marie-hendy', name:'Marie Hendy', role:'Customer Service', color:'#f97316', notes:[], feedback:[], expenses:[]}];
const blank = {
  tasks:[], contacts:[], deals:[], tickets:[], team:defaultTeam, events:[], expenses:[], logs:[], notes:[],
  inbox:[], goals:[], automations:[], wins:[],
  settings:{theme:'dark', monthlyBudget:0, weeklyCalls:20, weeklyFollowups:30, weeklyTickets:25, focusMode:false}
};
let migrated = migrateKeys.map(k=>localStorage.getItem(k)).find(Boolean);
let data = JSON.parse(localStorage.getItem(storeKey) || migrated || JSON.stringify(blank));
data = {...blank, ...data, settings:{...blank.settings,...(data.settings||{})}, team:(data.team&&data.team.length?data.team:defaultTeam)};
data.contacts = (data.contacts||[]).map(c=>({favorite:false, health:70, lastContact:'', notes:[], ...c}));
data.team = (data.team||[]).map((m,i)=>({color:teamColours[i%teamColours.length], notes:[], feedback:[], expenses:[], capacity:80, ...m}));
data.tasks ??=[]; data.events ??=[]; data.expenses ??=[]; data.logs ??=[]; data.inbox ??=[]; data.goals ??=[]; data.automations ??=[]; data.wins ??=[];
if(!localStorage.getItem(storeKey)) localStorage.setItem(storeKey, JSON.stringify(data));
let route = location.hash?.replace('#','') || 'dashboard';
let calDate = new Date();
let contactsView = 'all';
const navItems = [
 ['dashboard','🏠 Command'],['focus','🔥 Focus Now'],['calendar','📅 Calendar'],['tasks','✅ Tasks'],['contacts','👥 Contacts'],['pipeline','💼 Pipeline'],['team','🧑‍💼 Team'],['expenses','💷 Expenses'],['dailylog','📝 Daily Log'],['goals','🎯 Goals'],['automations','⚡ Automations'],['reports','📊 Reports'],['settings','⚙️ Settings']
];
function save(noRender=false){localStorage.setItem(storeKey, JSON.stringify(data)); if(!noRender) render();}
function setRoute(r){route=r; if(location.hash.replace('#','')!==r) location.hash=r; render();}
function toast(msg){const t=$('#toast'); if(!t) return; t.textContent=msg; t.classList.remove('hidden'); setTimeout(()=>t.classList.add('hidden'),2500)}
function init(){document.body.classList.toggle('light', data.settings.theme==='light'); updateClock(); setInterval(updateClock,1000); $('#quickAddBtn').onclick=quickAdd; $('#quickInput').addEventListener('keydown',e=>{if(e.key==='Enter')quickAdd(); if(e.key==='/' && e.ctrlKey)actions.commandPalette();}); $('#clearData').onclick=()=>{ if(confirm('Clear all Command Centre data from this device?')){data=JSON.parse(JSON.stringify(blank)); save();}}; $('#closeModal').onclick=closeModal; $('#themeBtn').onclick=()=>actions.themeToggle(); $('#commandBtn').onclick=()=>actions.commandPalette(); document.addEventListener('keydown',e=>{if(e.key==='/' && !['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault(); actions.commandPalette();}}); runAutomations(); render();}
function updateClock(){const el=$('#todayText'); if(el) el.textContent = new Date().toLocaleString('en-GB',{weekday:'long', day:'numeric', month:'long', year:'numeric', hour:'2-digit', minute:'2-digit'});}
function openModal(html){$('#modalContent').innerHTML=html; $('#modal').classList.remove('hidden'); bind();}
function closeModal(){ $('#modal').classList.add('hidden'); $('#modalContent').innerHTML=''; }
function pageTitle(){return navItems.find(x=>x[0]===route)?.[1].replace(/^\S+\s/,'')||'Command'}
window.addEventListener('hashchange',()=>{ const r=location.hash.replace('#','')||'dashboard'; if(navItems.some(x=>x[0]===r)){ route=r; render(); }});
function render(){ $('#pageTitle').textContent = pageTitle(); $('#nav').innerHTML = navItems.map(([id,label])=>`<button class="navbtn ${route===id?'active':''}" onclick="setRoute('${id}')"><span>${label}</span><span>›</span></button>`).join(''); const views={dashboard,focus,calendar,tasks,contacts,pipeline,team,expenses,dailylog,goals,automations,reports,settings}; $('#view').innerHTML = `<div class="view-enter">${(views[route]||dashboard)()}</div>`; bind();}
function bind(){ $$('[data-action]').forEach(btn=>btn.onclick=()=>actions[btn.dataset.action]?.(btn.dataset)); $$('.drop').forEach(lane=>{lane.ondragover=e=>e.preventDefault(); lane.ondrop=e=>{const [type,id]=e.dataTransfer.getData('text').split(':'); if(type==='deal'){const x=data.deals.find(x=>x.id===id); if(x)x.stage=lane.dataset.stage} if(type==='ticket'){const x=data.tickets.find(x=>x.id===id); if(x)x.status=lane.dataset.stage} save();};}); $$('.calendar-day').forEach(day=>{day.ondragover=e=>e.preventDefault(); day.ondrop=e=>{const [type,id]=e.dataTransfer.getData('text').split(':'); if(type==='event'){const ev=data.events.find(x=>x.id===id); if(ev){ev.date=day.dataset.date; save(); toast('Event moved');}}}; day.ondblclick=()=>actions.eventForm({date:day.dataset.date});}); $$('.drag,.event-drag').forEach(el=>{el.draggable=true; el.ondragstart=e=>e.dataTransfer.setData('text', el.dataset.drag);});}
function stats(){ const today=todayISO(), month=today.slice(0,7); const weekDays = lastNDays(7); return {openTasks:data.tasks.filter(t=>!t.done).length, doneToday:data.tasks.filter(t=>t.done&&t.doneDate===today).length, pipeline:data.deals.reduce((a,d)=>a+Number(d.value||0),0), weighted:data.deals.reduce((a,d)=>a+Number(d.value||0)*(Number(d.prob||0)/100),0), tickets:data.tickets.filter(t=>t.status!=='Resolved').length, escalated:data.tickets.filter(t=>t.priority==='High'&&t.status!=='Resolved').length, meetings:data.events.filter(e=>e.date===today).length, expenses:data.expenses.filter(e=>e.date?.startsWith(month)).reduce((a,e)=>a+Number(e.amount||0),0), faves:data.contacts.filter(c=>c.favorite).length, calls:data.tasks.filter(t=>/call/i.test(t.title||'')&&weekDays.includes(t.date)).length, followups:data.tasks.filter(t=>/follow|email|chase/i.test(t.title||'')&&weekDays.includes(t.date)).length, resolved:data.tickets.filter(t=>t.status==='Resolved').length};}
function nextActions(){let a=[]; const now=todayISO(); data.deals.filter(d=>d.stage!=='Won'&&d.stage!=='Lost'&&(!d.next || d.next<=now)).forEach(d=>a.push({type:'💼 Sales',title:d.name,detail:`Follow-up due · ${money(d.value)} · ${d.prob||0}%`,route:'pipeline',score:80+Number(d.value||0)/1000})); data.events.filter(e=>e.date===now).forEach(e=>a.push({type:'📅 Today',title:e.title,detail:e.teamId?`${teamName(e.teamId)} · ${e.type}`:(e.time||e.type||'Today'),route:'calendar',score:75})); data.tasks.filter(t=>!t.done && (!t.date || t.date<=now)).forEach(t=>a.push({type:'✅ Task',title:t.title,detail:t.date||'No date',route:'tasks',score:t.date&&t.date<now?90:60})); data.contacts.filter(c=>c.favorite && c.lastContact && daysSince(c.lastContact)>7).forEach(c=>a.push({type:'⭐ Contact',title:`Check in with ${c.name}`,detail:`${daysSince(c.lastContact)} days since last contact`,route:'contacts',score:72})); const budget=Number(data.settings.monthlyBudget||0); const spent=stats().expenses; if(budget && spent>budget)a.push({type:'💷 Budget',title:'Monthly budget exceeded',detail:`${money(spent)} spent vs ${money(budget)}`,route:'expenses',score:95}); return a.sort((x,y)=>y.score-x.score).slice(0,10);}
function morningBrief(){const today=todayISO(); const todaysEvents=data.events.filter(e=>e.date===today).sort((a,b)=>String(a.time||'99:99').localeCompare(String(b.time||'99:99'))); const leave=data.events.filter(e=>e.date===today && e.type==='Annual Leave'); const overdue=data.tasks.filter(t=>!t.done && t.date && t.date<today); const spendToday=data.expenses.filter(e=>e.date===today).reduce((a,e)=>a+Number(e.amount||0),0); return `<div class="hero power morning-brief"><span class="pill pulse">🧠 Morning Brief</span><h2>${todaysEvents.length?`${todaysEvents.length} diary item${todaysEvents.length>1?'s':''} today`:'Clear diary today'}</h2><div class="brief-grid"><div><b>📅 First up</b><p>${todaysEvents[0]?`${todaysEvents[0].time||'All day'} · ${todaysEvents[0].title}`:'No meetings yet'}</p></div><div><b>🔥 Priorities</b><p>${nextActions().length} focus actions ready</p></div><div><b>👥 Team</b><p>${leave.length?leave.map(e=>teamName(e.teamId)).join(', ')+' on leave':'No leave logged today'}</p></div><div><b>💷 Spend today</b><p>${money(spendToday)}</p></div></div><div class="actions"><button onclick="setRoute('focus')">Open Focus Now</button><button class="ghost" onclick="setRoute('calendar')">Open Calendar</button></div></div>`;}
function teamWorkload(m){const today=todayISO(); const tasks=data.tasks.filter(t=>!t.done && t.owner===m.id).length; const events=data.events.filter(e=>e.teamId===m.id && e.date>=today).length; const feedback=(m.feedback||[]).length; const load=Math.min(100,(tasks*18)+(events*10)); return {tasks,events,feedback,load,status:load>75?'Busy':load>35?'Steady':'Available'};}
function dashboard(){const s=stats(), a=nextActions(), budget=Number(data.settings.monthlyBudget||0), pct=budget?Math.min(100,Math.round(s.expenses/budget*100)):0, top=a[0]; return morningBrief()+`<div class="hero power"><span class="pill pulse">🚀 Ridiculously Powerful Mode</span><h2>${top?top.title:'Your Command Centre is ready'}</h2><p class="muted">${top?`${top.type} · ${top.detail}`:'Use Quick Command or press / to capture anything fast.'}</p><div class="actions"><button data-action="commandPalette">⚡ Quick Command</button><button class="ghost" onclick="setRoute('focus')">🔥 Focus Now</button><button class="ghost" data-action="reviewForm">🧠 Daily Review</button></div></div>
<div class="grid cols-4">${metric('📅 Today',s.meetings,'calendar events','calendar')}${metric('🔥 Focus',a.length,'smart actions','focus')}${metric('💼 Forecast',money(s.weighted),'weighted pipeline','pipeline')}${metric('💷 Spend',money(s.expenses),budget?`${pct}% of budget`:'this month','expenses')}</div>
<div class="grid cols-2" style="margin-top:16px"><div class="card colour-card"><div class="calendar-head"><h3>Autopilot Priorities</h3><span class="pill">auto-ranked</span></div><div class="list">${actionList(a)}</div></div><div class="card teal-card"><div class="calendar-head"><h3>Today Timeline</h3><button class="ghost" data-action="eventForm">+</button></div><div class="list">${timeline(todayISO())}</div></div></div>
<div class="grid cols-3" style="margin-top:16px"><div class="card purple-card"><h3>Target Rings</h3>${ring('Calls',s.calls,data.settings.weeklyCalls)}${ring('Follow-ups',s.followups,data.settings.weeklyFollowups)}</div><div class="card blue-card"><h3>Expense Pulse</h3>${categoryBars(['Fuel','Car Hire','Hotels','Food','Misc'])}<div class="actions"><button class="ghost" data-action="expenseForm">Add Expense</button><button class="ghost" data-action="budgetForm">Budget</button></div></div><div class="card pink-card"><h3>Command Feed</h3>${activityFeed()}</div></div>`;}
function focus(){const a=nextActions(); return `<div class="hero focus-hero"><span class="pill">🔥 Focus Mode</span><h2>Do these first</h2><p class="muted">Your system ranks sales, team, expenses, contacts and diary items into one clear action list.</p></div><div class="grid cols-2"><div class="card"><h3>Focus Queue</h3><div class="list">${actionList(a,true)}</div></div><div class="card"><h3>Capture Inbox</h3><p class="muted">Throw messy thoughts here, process them later.</p><div class="actions"><button data-action="inboxForm">Add Inbox Item</button><button class="ghost" data-action="processInbox">Process Oldest</button></div><div class="list">${data.inbox.length?data.inbox.map(i=>`<div class="item"><div><h3>${i.text}</h3><p class="muted">${i.date}</p></div><button class="ghost" data-action="deleteInbox" data-id="${i.id}">Done</button></div>`).join(''):'<div class="empty">Inbox clear.</div>'}</div></div></div>`}
function calendar(){const y=calDate.getFullYear(), m=calDate.getMonth(); const first=new Date(y,m,1), start=(first.getDay()+6)%7, days=new Date(y,m+1,0).getDate(); let cells=''; for(let i=0;i<start;i++)cells+='<div class="day muted-day"></div>'; for(let d=1;d<=days;d++){const iso=localISO(new Date(y,m,d)); const ev=data.events.filter(e=>e.date===iso).sort((a,b)=>String(a.time||'99:99').localeCompare(String(b.time||'99:99'))); const isToday=iso===todayISO(); cells+=`<div class="day calendar-day ${isToday?'today':''}" data-date="${iso}"><div class="daynum"><b>${d}</b><button class="mini" data-action="eventForm" data-date="${iso}" title="Add event">+</button></div>${ev.slice(0,4).map(e=>`<div class="event event-drag ${e.type==='Annual Leave'?'leave':''}" data-drag="event:${e.id}" style="--event:${eventColour(e)}" title="${e.time?e.time+' · ':''}${e.title}">${eventIcon(e.type)} ${e.time?`<b>${e.time}</b> `:''}${e.title}</div>`).join('')}${ev.length>4?`<span class="muted">+${ev.length-4} more</span>`:''}</div>`;} return `<div class="calendar-head"><div><h3>${calDate.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h3><p class="muted">Full month overview · double-click a day to add · drag events between days.</p></div><div class="actions"><button class="ghost" data-action="prevMonth">‹</button><button data-action="todayMonth">Today</button><button class="ghost" data-action="nextMonth">›</button><button data-action="eventForm">Add Event</button></div></div><div class="legend">${data.team.map(m=>`<span class="team-chip" style="--member:${m.color}">${avatar(m.name)} ${m.name}</span>`).join('')}<span class="team-chip" style="--member:#7c3aed">Personal</span><span class="team-chip" style="--member:#38bdf8">Meetings</span></div><div class="calendar-grid weekdays">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<b>${x}</b>`).join('')}</div><div class="calendar-grid month-view">${cells}</div>`;}
function tasks(){return `<div class="page-actions"><button data-action="taskForm">Add Task</button><button class="ghost" data-action="recurringTaskForm">Recurring Task</button></div><div class="grid cols-2"><div class="card"><h3>Open Tasks</h3><div class="list">${data.tasks.filter(t=>!t.done).map(t=>taskItem(t)).join('')||'<div class="empty">No open tasks.</div>'}</div></div><div class="card"><h3>Completed</h3><div class="list">${data.tasks.filter(t=>t.done).slice(-20).reverse().map(t=>taskItem(t)).join('')||'<div class="empty">Nothing completed yet.</div>'}</div></div></div>`}
function contacts(){const list=contactsView==='favourites'?data.contacts.filter(c=>c.favorite):data.contacts; return `<div class="page-actions"><button data-action="contactForm">Add Contact</button><label class="inline-filter">View <select onchange="contactsView=this.value; render()"><option value="all" ${contactsView==='all'?'selected':''}>All contacts</option><option value="favourites" ${contactsView==='favourites'?'selected':''}>⭐ Favourite contacts</option></select></label></div>${contactsView==='favourites'?'<div class="hero mini-hero"><h2>⭐ Favourite Contacts</h2><p class="muted">Your most important people, kept inside Contacts.</p></div>':''}<div class="grid cards-grid">${list.map(contactCard).join('')||'<div class="empty">No contacts in this view yet.</div>'}</div>`}
function pipeline(){const stages=['Lead','Qualified','Proposal','Won']; return `<div class="page-actions"><button data-action="dealForm">Add Deal</button></div><div class="kanban">${stages.map(st=>`<div class="lane drop" data-stage="${st}"><h3>${stageIcon(st)} ${st}</h3>${data.deals.filter(d=>d.stage===st).map(d=>`<div class="item drag deal-card" data-drag="deal:${d.id}"><div><h3>${d.name}</h3><p class="muted">${money(d.value)} · ${d.prob||0}% · next ${d.next||'none'}</p><div class="bar"><span style="width:${d.prob||0}%"></span></div></div></div>`).join('')||'<p class="muted">Drop deals here</p>'}</div>`).join('')}</div>`}
function service(){const stages=['New','In Progress','Waiting','Resolved']; return `<div class="page-actions"><button data-action="ticketForm">New Ticket</button></div><div class="kanban">${stages.map(st=>`<div class="lane drop" data-stage="${st}"><h3>🎧 ${st}</h3>${data.tickets.filter(t=>t.status===st).map(t=>`<div class="item drag ${t.priority==='High'?'priority-item urgent':''}" data-drag="ticket:${t.id}"><div><h3>${t.title}</h3><p class="muted">${t.priority||'Normal'} priority</p></div></div>`).join('')||'<p class="muted">Drop tickets here</p>'}</div>`).join('')}</div>`}
function team(){return `<div class="page-actions"><button data-action="teamForm">Add Team Member</button></div><div class="grid cols-3">${data.team.map(m=>{const w=teamWorkload(m); const exp=data.expenses.filter(e=>e.teamId===m.id).reduce((a,e)=>a+Number(e.amount||0),0); const todayLeave=data.events.some(e=>e.teamId===m.id&&e.date===todayISO()&&e.type==='Annual Leave'); return `<div class="card member-card" style="--member:${m.color}"><div class="member-banner"></div><div class="member-row">${avatar(m.name)}<div><h3>${m.name}</h3><p class="muted">${m.role||'Team member'} · ${todayLeave?'On leave today':w.status}</p></div></div><div class="bar big"><span style="width:${w.load}%"></span></div><div class="team-score"><span>Workload <b>${w.load}%</b></span><span>Upcoming <b>${w.events}</b></span><span>Feedback <b>${w.feedback}</b></span><span>Expenses <b>${money(exp)}</b></span></div><div class="actions"><button data-action="teamDetail" data-id="${m.id}">Open profile</button><button class="ghost" onclick="actions.eventForm({teamId:'${m.id}'})">Leave/Event</button></div></div>`}).join('')}</div>`}
function expenses(){const cats=['Fuel','Car Hire','Hotels','Food','Misc']; return `<div class="page-actions"><button data-action="expenseForm">Add Expense</button><button class="ghost" data-action="exportExpenses">Export CSV</button><button class="ghost" data-action="budgetForm">Budget</button></div><div class="grid cols-2"><div class="card"><h3>By Category</h3>${categoryBars(cats)}</div><div class="card"><h3>Latest Expenses</h3><div class="list">${data.expenses.slice(-30).reverse().map(e=>`<div class="item"><div><h3>${catIcon(e.category)} ${e.category} ${money(e.amount)}</h3><p class="muted">${e.date} ${e.teamId?'· '+teamName(e.teamId):''} · ${e.note||''}</p></div></div>`).join('')||'<div class="empty">No expenses yet.</div>'}</div></div></div>`}
function dailylog(){return `<div class="page-actions"><button data-action="logForm">Add Daily Log</button><button class="ghost" data-action="reviewForm">Guided Review</button></div><div class="grid cards-grid">${data.logs.slice().reverse().map(l=>`<div class="card"><span class="pill">${l.date}</span><h3>Wins</h3><p>${l.wins||'—'}</p><h3>Issues</h3><p>${l.issues||'—'}</p><h3>Ideas</h3><p>${l.ideas||'—'}</p><h3>Next</h3><p>${l.next||'—'}</p></div>`).join('')||'<div class="empty">No logs yet.</div>'}</div>`}
function goals(){return `<div class="page-actions"><button data-action="goalForm">Add Goal</button></div><div class="grid cards-grid">${data.goals.map(g=>`<div class="card goal-card"><span class="pill">${g.area}</span><h3>${g.title}</h3><p class="muted">Target: ${g.target} · Current: ${g.current}</p><div class="bar big"><span style="width:${Math.min(100,Math.round(Number(g.current||0)/Number(g.target||1)*100))}%"></span></div><div class="actions"><button data-action="updateGoal" data-id="${g.id}">Update</button><button class="ghost" data-action="deleteGoal" data-id="${g.id}">Delete</button></div></div>`).join('')||'<div class="empty">Add weekly or monthly goals.</div>'}</div>`}
function automations(){return `<div class="hero mini-hero"><h2>⚡ Automation Rules</h2><p class="muted">Local automations that generate prompts and keep things moving.</p></div><div class="grid cols-2"><div class="card"><h3>Suggested Rules</h3><div class="list"><div class="item"><div><h3>Daily review reminder</h3><p class="muted">Creates a task every weekday.</p></div><button data-action="addAutomation" data-kind="dailyReview">Add</button></div><div class="item"><div><h3>Weekly expense check</h3><p class="muted">Creates a Friday expense review task.</p></div><button data-action="addAutomation" data-kind="expenseReview">Add</button></div><div class="item"><div><h3>Follow-up favourites</h3><p class="muted">Flags favourite contacts after 7 days.</p></div><button data-action="addAutomation" data-kind="favFollowup">Add</button></div></div></div><div class="card"><h3>Active Rules</h3><div class="list">${data.automations.map(a=>`<div class="item"><div><h3>${a.name}</h3><p class="muted">${a.kind}</p></div><button class="ghost" data-action="deleteAutomation" data-id="${a.id}">Remove</button></div>`).join('')||'<div class="empty">No rules yet.</div>'}</div></div></div>`}
function reports(){const s=stats(); return `<div class="hero mini-hero"><h2>📊 Weekly Review</h2><p class="muted">A ready-made snapshot for your weekly update.</p><div class="actions"><button data-action="copyWeeklyReport">Copy Weekly Report</button><button class="ghost" data-action="exportExpenses">Export Expenses</button></div></div><div class="grid cols-5">${metric('Done Today',s.doneToday,'tasks','tasks')}${metric('Open Tasks',s.openTasks,'remaining','tasks')}${metric('Contacts',data.contacts.length,'total','contacts')}${metric('Team',data.team.length,'members','team')}${metric('Spend',money(s.expenses),'this month','expenses')}</div><div class="grid cols-2" style="margin-top:16px"><div class="card"><h3>Weekly Review Snapshot</h3><p>Calls: ${s.calls}/${data.settings.weeklyCalls}</p><p>Follow-ups: ${s.followups}/${data.settings.weeklyFollowups}</p><p>Weighted pipeline: ${money(s.weighted)}</p><button data-action="copyWeeklyReport">Copy Weekly Report</button></div><div class="card"><h3>Expense Export</h3><p class="muted">Download your full expenses as CSV.</p><button data-action="exportExpenses">Export CSV</button></div></div>`}
function settings(){return `<div class="grid cols-2"><div class="card"><h3>Theme</h3><p class="muted">Current: ${data.settings.theme}</p><button data-action="themeToggle">Toggle Theme</button></div><div class="card"><h3>Targets</h3><p class="muted">Weekly activity targets power the dashboard rings.</p><button data-action="targetsForm">Edit Targets</button></div><div class="card"><h3>Budget</h3><p class="muted">Current: ${money(data.settings.monthlyBudget)}</p><button data-action="budgetForm">Set Budget</button></div><div class="card"><h3>Backup</h3><button data-action="exportBackup">Export Backup JSON</button><button class="ghost" data-action="importBackup">Import Backup</button></div></div>`}
function metric(label,val,sub,route){return `<div class="metric" onclick="setRoute('${route}')"><span class="pill">${label}</span><strong>${val}</strong><p>${sub}</p></div>`}
function actionList(a,done=false){return a.length?a.map((x,i)=>`<div class="item priority-item ${i===0?'urgent':i===1?'warn':''}"><div><span class="pill">${x.type}</span><h3>${x.title}</h3><p class="muted">${x.detail}</p></div><button class="ghost" onclick="setRoute('${x.route}')">Open</button></div>`).join(''):'<div class="empty">Nothing urgent. Add work to unlock autopilot.</div>'}
function timeline(date){const ev=data.events.filter(e=>e.date===date).sort((a,b)=>(a.time||'').localeCompare(b.time||'')); return ev.length?ev.map(e=>`<div class="item"><div><h3><span style="color:${eventColour(e)}">${eventIcon(e.type)}</span> ${e.title}</h3><p class="muted">${e.time||'All day'} · ${e.type||'Event'} ${e.teamId?'· '+teamName(e.teamId):''}</p></div></div>`).join(''):'<div class="empty">Nothing scheduled yet.</div>'}
function taskItem(t){return `<div class="item task-rich ${t.priority==='High'?'priority-item urgent':t.priority==='Medium'?'priority-item warn':''}"><div><label class="check"><input type="checkbox" ${t.done?'checked':''} data-action="toggleTask" data-id="${t.id}"> <span>${t.title}</span></label><p class="muted">${t.category||'General'} · ${t.priority||'Normal'} priority ${t.owner?'· '+t.owner:''}</p>${t.details?`<p>${t.details}</p>`:''}</div><span class="pill">${t.date||'No date'}${t.time?' · '+t.time:''}</span></div>`}
function contactCard(c){return `<div class="card contact-card"><div class="member-row"><div class="avatar ${c.favorite?'fav':''}">${c.favorite?'⭐':initials(c.name)}</div><div><h3>${c.name||'Unnamed'}</h3><p class="muted">${c.company||''}</p></div></div><div class="bar"><span style="width:${contactHealth(c)}%"></span></div><p class="muted">Health ${contactHealth(c)}% ${c.lastContact?'· last '+c.lastContact:''}</p><div class="actions"><button class="ghost" data-action="toggleFavorite" data-id="${c.id}">${c.favorite?'Unstar':'Favourite'}</button><button data-action="contactNote" data-id="${c.id}">Note</button><button class="ghost" data-action="contactForm" data-id="${c.id}">Edit</button></div></div>`}
function categoryBars(cats){const total=data.expenses.reduce((a,e)=>a+Number(e.amount||0),0)||1; return cats.map(c=>{const v=data.expenses.filter(e=>e.category===c).reduce((a,e)=>a+Number(e.amount||0),0); return `<div class="statline"><span>${catIcon(c)} ${c}</span><b>${money(v)}</b></div><div class="bar"><span style="width:${Math.round(v/total*100)}%"></span></div>`}).join('')}
function ring(label,current,target){const p=Math.min(100,Math.round(Number(current||0)/Number(target||1)*100)); return `<div class="ring-row"><div class="ring" style="--p:${p}"><span>${p}%</span></div><div><h3>${label}</h3><p class="muted">${current}/${target} this week</p></div></div>`}
function activityFeed(){const items=[...data.tasks.map(x=>['✅',x.title,x.date]),...data.events.map(x=>['📅',x.title,x.date]),...data.expenses.map(x=>['💷',`${x.category} ${money(x.amount)}`,x.date])].filter(x=>x[2]).sort((a,b)=>String(b[2]).localeCompare(String(a[2]))).slice(0,7); return items.length?items.map(i=>`<div class="feed"><span>${i[0]}</span><div>${i[1]}<p class="muted">${i[2]}</p></div></div>`).join(''):'<p class="muted">Activity appears here.</p>'}
function lastNDays(n){return Array.from({length:n},(_,i)=>localISO(new Date(Date.now()-i*86400000)));}
function daysSince(iso){return Math.floor((new Date(todayISO())-new Date(iso))/86400000)}
function teamName(id){return data.team.find(m=>m.id===id)?.name||''}
function eventColour(e){return e.teamId?(data.team.find(m=>m.id===e.teamId)?.color||'#38bdf8'):{Meeting:'#38bdf8',Sales:'#22c55e',Personal:'#a78bfa','Annual Leave':'#f97316','Team Event':'#14b8a6'}[e.type]||'#7c3aed'}
function eventIcon(t){return {'Meeting':'📅','Sales':'💼','Personal':'✨','Annual Leave':'🌴','Team Event':'👥'}[t]||'📌'}
function catIcon(c){return {'Fuel':'⛽','Car Hire':'🚗','Hotels':'🏨','Food':'🍽️','Misc':'💷'}[c]||'💷'}
function stageIcon(s){return {Lead:'🌱',Qualified:'✅',Proposal:'📨',Won:'🏆'}[s]||'💼'}
function initials(n=''){return n.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()||'?' }
function avatar(n){return `<span class="avatar small">${initials(n)}</span>`}
function contactHealth(c){let h=60; if(c.favorite)h+=10; if(c.lastContact){const d=daysSince(c.lastContact); h += d<7?20:d<14?5:-15;} if((c.notes||[]).length)h+=5; return Math.max(5,Math.min(100,h));}
function runAutomations(){const today=todayISO(); const exists=title=>data.tasks.some(t=>t.title===title&&t.date===today); data.automations.forEach(a=>{if(a.kind==='dailyReview' && !exists('Daily review')) data.tasks.push({id:uid(),title:'Daily review',date:today,done:false}); if(a.kind==='expenseReview' && new Date().getDay()===5 && !exists('Weekly expense review')) data.tasks.push({id:uid(),title:'Weekly expense review',date:today,done:false});}); save(true);}
const options=(arr,val='')=>arr.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('');
const teamOptions=id=>`<option value="">None / Personal</option>${data.team.map(m=>`<option value="${m.id}" ${m.id===id?'selected':''}>${m.name}</option>`).join('')}`;
const actions={
 themeToggle(){data.settings.theme=data.settings.theme==='dark'?'light':'dark'; document.body.classList.toggle('light',data.settings.theme==='light'); save();}, prevMonth(){calDate.setMonth(calDate.getMonth()-1); render()}, nextMonth(){calDate.setMonth(calDate.getMonth()+1); render()}, todayMonth(){calDate=new Date(); render()},
 toggleTask({id}){const t=data.tasks.find(t=>t.id===id); t.done=!t.done; t.doneDate=t.done?todayISO():''; save()},
 taskForm(ds={}){openModal(`<h2>Add Task</h2><div class="form"><input id="f_title" placeholder="Task title" value="${ds.title||''}"><div class="form-row"><input id="f_date" type="date" value="${todayISO()}"><input id="f_time" type="time"></div><div class="form-row"><select id="f_priority">${options(['Normal','Medium','High'])}</select><select id="f_category">${options(['General','Sales','Admin','Customer','Personal','Finance'])}</select></div><div class="form-row"><input id="f_owner" placeholder="Owner / person responsible"><select id="f_contact"><option value="">No linked contact</option>${data.contacts.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></div><textarea id="f_details" placeholder="Details, outcome needed, links or notes"></textarea><button onclick="actions.saveTask()">Save Task</button></div>`)}, saveTask(){data.tasks.push({id:uid(),title:$('#f_title').value,date:$('#f_date').value,time:$('#f_time').value,priority:$('#f_priority').value,category:$('#f_category').value,owner:$('#f_owner').value,contactId:$('#f_contact').value,details:$('#f_details').value,done:false}); closeModal(); save()}, recurringTaskForm(){openModal(`<h2>Recurring Task</h2><div class="form"><input id="f_title" placeholder="Task name"><select id="f_freq">${options(['Daily','Weekly','Monthly'])}</select><button onclick="actions.saveRecurringTask()">Create Rule</button></div>`)}, saveRecurringTask(){data.automations.push({id:uid(),name:`${$('#f_freq').value} task: ${$('#f_title').value}`,kind:'task',title:$('#f_title').value,frequency:$('#f_freq').value}); closeModal(); save()},
 contactForm(ds={}){const c=data.contacts.find(x=>x.id===ds.id)||{}; openModal(`<h2>${c.id?'Edit':'Add'} Contact</h2><div class="form"><input id="f_name" placeholder="Name" value="${c.name||''}"><input id="f_company" placeholder="Company" value="${c.company||''}"><input id="f_email" placeholder="Email" value="${c.email||''}"><input id="f_phone" placeholder="Phone" value="${c.phone||''}"><input id="f_last" type="date" value="${c.lastContact||''}"><label class="check"><input id="f_fav" type="checkbox" ${c.favorite?'checked':''}> Favourite contact</label><button onclick="actions.saveContact('${c.id||''}')">Save Contact</button></div>`)}, saveContact(id){const obj={id:id||uid(),name:$('#f_name').value,company:$('#f_company').value,email:$('#f_email').value,phone:$('#f_phone').value,lastContact:$('#f_last').value,favorite:$('#f_fav').checked,notes:(data.contacts.find(x=>x.id===id)?.notes)||[]}; if(id)Object.assign(data.contacts.find(x=>x.id===id),obj); else data.contacts.push(obj); closeModal(); save()}, toggleFavorite({id}){const c=data.contacts.find(x=>x.id===id); c.favorite=!c.favorite; save(); toast(c.favorite?'Added to favourites':'Removed from favourites')}, contactNote({id}){const txt=prompt('Contact note'); if(txt){const c=data.contacts.find(x=>x.id===id); c.notes??=[]; c.notes.push({date:todayISO(),text:txt}); c.lastContact=todayISO(); save();}},
 dealForm(){openModal(`<h2>Add Deal</h2><div class="form"><input id="f_name" placeholder="Deal name"><input id="f_value" type="number" placeholder="Value"><input id="f_prob" type="number" placeholder="Probability %"><select id="f_stage">${options(['Lead','Qualified','Proposal','Won'])}</select><input id="f_next" type="date" value="${todayISO()}"><button onclick="actions.saveDeal()">Save Deal</button></div>`)}, saveDeal(){data.deals.push({id:uid(),name:$('#f_name').value,value:$('#f_value').value,prob:$('#f_prob').value,stage:$('#f_stage').value,next:$('#f_next').value}); closeModal(); save()},
 ticketForm(){openModal(`<h2>New Ticket</h2><div class="form"><input id="f_title" placeholder="Issue / ticket title"><select id="f_priority">${options(['Normal','High'])}</select><select id="f_status">${options(['New','In Progress','Waiting','Resolved'])}</select><button onclick="actions.saveTicket()">Save Ticket</button></div>`)}, saveTicket(){data.tickets.push({id:uid(),title:$('#f_title').value,priority:$('#f_priority').value,status:$('#f_status').value}); closeModal(); save()},
 eventForm(ds={}){openModal(`<h2>Add Calendar Event</h2><div class="form"><div class="form-row"><input id="f_date" type="date" value="${ds.date||todayISO()}"><input id="f_time" type="time"></div><input id="f_title" placeholder="Meeting, event, annual leave..."><div class="form-row"><select id="f_type">${options(['Meeting','Sales','Personal','Annual Leave','Team Event'])}</select><select id="f_team">${teamOptions(ds.teamId||'')}</select></div><textarea id="f_note" placeholder="Notes, attendees, location or outcome"></textarea><button onclick="actions.saveEvent()">Save Event</button></div>`)}, saveEvent(){data.events.push({id:uid(),date:$('#f_date').value,time:$('#f_time').value,title:$('#f_title').value,type:$('#f_type').value,teamId:$('#f_team').value,note:$('#f_note').value}); closeModal(); save()},
 expenseForm(ds={}){openModal(`<h2>Add Expense</h2><div class="form"><div class="form-row"><input id="f_date" type="date" value="${todayISO()}"><input id="f_amount" type="number" placeholder="Amount"></div><select id="f_cat">${options(['Fuel','Car Hire','Hotels','Food','Misc'])}</select><select id="f_team">${teamOptions(ds.teamId||'')}</select><input id="f_note" placeholder="Notes / receipt reference"><button onclick="actions.saveExpense()">Save Expense</button></div>`)}, saveExpense(){const e={id:uid(),date:$('#f_date').value,amount:$('#f_amount').value,category:$('#f_cat').value,teamId:$('#f_team').value,note:$('#f_note').value}; data.expenses.push(e); closeModal(); save()},
 teamForm(){openModal(`<h2>Add Team Member</h2><div class="form"><input id="f_name" placeholder="Name"><input id="f_role" placeholder="Role"><input id="f_color" type="color" value="#38bdf8"><input id="f_email" placeholder="Email"><input id="f_phone" placeholder="Phone"><button onclick="actions.saveTeam()">Save Team Member</button></div>`)}, saveTeam(){data.team.push({id:uid(),name:$('#f_name').value,role:$('#f_role').value,color:$('#f_color').value,email:$('#f_email').value,phone:$('#f_phone').value,notes:[],feedback:[],expenses:[]}); closeModal(); save()}, teamDetail({id}){const m=data.team.find(x=>x.id===id); const ex=data.expenses.filter(e=>e.teamId===id); const ev=data.events.filter(e=>e.teamId===id).sort((a,b)=>String(a.date).localeCompare(String(b.date))); const noteCount=(m.notes||[]).length, fbCount=(m.feedback||[]).length; openModal(`<div class="team-detail" style="--member:${m.color}"><div class="member-banner"></div><div class="profile-hero">${avatar(m.name)}<div><h2>${m.name}</h2><p class="muted">${m.role||''} ${m.email?'· '+m.email:''} ${m.phone?'· '+m.phone:''}</p></div></div><div class="profile-stats"><span>Notes <b>${noteCount}</b></span><span>Feedback <b>${fbCount}</b></span><span>Expenses <b>${money(ex.reduce((a,e)=>a+Number(e.amount||0),0))}</b></span><span>Calendar <b>${ev.length}</b></span></div><div class="actions"><button onclick="actions.addTeamNote('${id}')">Add Note</button><button onclick="actions.addTeamFeedback('${id}')">Add Feedback</button><button onclick="actions.expenseForm({teamId:'${id}'})">Add Expense</button><button class="ghost" onclick="actions.eventForm({teamId:'${id}'})">Add Calendar Event</button></div><div class="grid cols-2"><div class="card"><h3>📝 Notes</h3>${(m.notes||[]).map(n=>`<p class="note"><b>${n.date}</b><br>${n.text}</p>`).join('')||'<p class="muted">No notes yet.</p>'}</div><div class="card"><h3>💬 Feedback</h3>${(m.feedback||[]).map(n=>`<p class="note"><b>${n.date}</b><br>${n.text}</p>`).join('')||'<p class="muted">No feedback yet.</p>'}</div><div class="card"><h3>💷 Expenses</h3>${ex.map(e=>`<p class="note"><b>${e.date}</b><br>${catIcon(e.category)} ${e.category} · ${money(e.amount)}<br><span class="muted">${e.note||''}</span></p>`).join('')||'<p class="muted">No expenses yet.</p>'}</div><div class="card"><h3>📅 Calendar</h3>${ev.map(e=>`<p class="note"><b>${e.date} ${e.time||''}</b><br><span style="color:${eventColour(e)}">${eventIcon(e.type)}</span> ${e.title}<br><span class="muted">${e.type}</span></p>`).join('')||'<p class="muted">No calendar events yet.</p>'}</div></div></div>`)}, addTeamNote(id){const text=prompt('Add note'); if(text){data.team.find(m=>m.id===id).notes.push({date:todayISO(),text}); save(true); actions.teamDetail({id});}}, addTeamFeedback(id){const text=prompt('Add feedback'); if(text){data.team.find(m=>m.id===id).feedback.push({date:todayISO(),text}); save(true); actions.teamDetail({id});}},
logForm(){openModal(`<h2>Structured Daily Log</h2><div class="form"><input id="f_date" type="date" value="${todayISO()}"><textarea id="f_wins" placeholder="Wins"></textarea><textarea id="f_issues" placeholder="Issues"></textarea><textarea id="f_ideas" placeholder="Ideas"></textarea><textarea id="f_next" placeholder="Tomorrow / next actions"></textarea><button onclick="actions.saveLog()">Save Log</button></div>`)}, reviewForm(){actions.logForm()}, saveLog(){data.logs.push({id:uid(),date:$('#f_date').value,wins:$('#f_wins').value,issues:$('#f_issues').value,ideas:$('#f_ideas').value,next:$('#f_next').value}); closeModal(); save()},
 budgetForm(){openModal(`<h2>Monthly Budget</h2><div class="form"><input id="f_budget" type="number" value="${data.settings.monthlyBudget||0}"><button onclick="actions.saveBudget()">Save Budget</button></div>`)}, saveBudget(){data.settings.monthlyBudget=$('#f_budget').value; closeModal(); save()}, targetsForm(){openModal(`<h2>Weekly Targets</h2><div class="form"><input id="f_calls" type="number" value="${data.settings.weeklyCalls}" placeholder="Calls"><input id="f_follow" type="number" value="${data.settings.weeklyFollowups}" placeholder="Follow ups"><button onclick="actions.saveTargets()">Save Targets</button></div>`)}, saveTargets(){data.settings.weeklyCalls=$('#f_calls').value; data.settings.weeklyFollowups=$('#f_follow').value; closeModal(); save()},
 goalForm(){openModal(`<h2>Add Goal</h2><div class="form"><input id="f_title" placeholder="Goal"><select id="f_area">${options(['Sales','Team','Personal','Expenses','Development'])}</select><input id="f_target" type="number" placeholder="Target number"><input id="f_current" type="number" placeholder="Current progress" value="0"><button onclick="actions.saveGoal()">Save Goal</button></div>`)}, saveGoal(){data.goals.push({id:uid(),title:$('#f_title').value,area:$('#f_area').value,target:$('#f_target').value,current:$('#f_current').value}); closeModal(); save()}, updateGoal({id}){const g=data.goals.find(x=>x.id===id); const v=prompt('New current progress',g.current); if(v!==null){g.current=v; save();}}, deleteGoal({id}){data.goals=data.goals.filter(g=>g.id!==id); save()},
 inboxForm(){const text=prompt('Capture to inbox'); if(text){data.inbox.push({id:uid(),date:todayISO(),text}); save();}}, deleteInbox({id}){data.inbox=data.inbox.filter(i=>i.id!==id); save()}, processInbox(){const i=data.inbox[0]; if(!i)return toast('Inbox clear'); $('#quickInput').value=i.text; data.inbox.shift(); save();},
 addAutomation({kind}){const names={dailyReview:'Daily review reminder',expenseReview:'Weekly expense check',favFollowup:'Favourite contact follow-up'}; if(!data.automations.some(a=>a.kind===kind))data.automations.push({id:uid(),kind,name:names[kind]}); save();}, deleteAutomation({id}){data.automations=data.automations.filter(a=>a.id!==id); save()},
 commandPalette(){openModal(`<h2>⚡ Quick Command</h2><p class="muted">Press / anytime to open this. Capture anything in seconds.</p><div class="command-grid"><button onclick="actions.taskForm();">✅ Add task</button><button onclick="actions.eventForm();">📅 Add meeting / leave</button><button onclick="actions.expenseForm();">💷 Add expense</button><button onclick="actions.contactForm();">👥 Add contact</button><button onclick="actions.teamForm();">🧑‍💼 Add team member</button><button onclick="actions.dealForm();">💼 Add deal</button><button onclick="actions.goalForm();">🎯 Add goal</button><button onclick="actions.inboxForm();">📥 Capture inbox</button><button onclick="actions.logForm();">📝 Daily log</button></div>`)},
 exportExpenses(){const rows=[['Date','Category','Amount','Team Member','Note'],...data.expenses.map(e=>[e.date,e.category,e.amount,teamName(e.teamId),e.note])]; downloadCSV(rows,'command-centre-expenses.csv')}, copyWeeklyReport(){const s=stats(); const txt=`Weekly Command Centre Report\nCalls: ${s.calls}/${data.settings.weeklyCalls}\nFollow-ups: ${s.followups}/${data.settings.weeklyFollowups}\nWeighted pipeline: ${money(s.weighted)}\nMonthly spend: ${money(s.expenses)}`; navigator.clipboard?.writeText(txt); toast('Weekly report copied');}, exportBackup(){const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); a.download='command-centre-backup.json'; a.click();}, importBackup(){openModal(`<h2>Import Backup</h2><div class="form"><textarea id="f_json" placeholder="Paste backup JSON here"></textarea><button onclick="actions.saveImport()">Import</button></div>`)}, saveImport(){try{data=JSON.parse($('#f_json').value); closeModal(); save()}catch(e){toast('Invalid backup JSON')}}
};
function downloadCSV(rows,name){const csv=rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=name; a.click();}
function quickAdd(){const v=$('#quickInput').value.trim(); if(!v)return; const low=v.toLowerCase(); const amt=(v.match(/£?([0-9]+(?:\.[0-9]{1,2})?)/)||[])[1]; if(low.includes('fuel')||low.includes('hotel')||low.includes('car hire')||low.includes('expense')){data.expenses.push({id:uid(),date:todayISO(),amount:amt||0,category:low.includes('fuel')?'Fuel':low.includes('hotel')?'Hotels':low.includes('car hire')?'Car Hire':'Misc',note:v,teamId:''}); toast('Expense added');} else if(low.includes('meeting')||low.includes('annual leave')||low.includes('leave')){data.events.push({id:uid(),date:todayISO(),time:'',title:v,type:low.includes('leave')?'Annual Leave':'Meeting',teamId:'',note:''}); toast('Calendar event added');} else if(low.includes('call')||low.includes('follow')){data.tasks.push({id:uid(),title:v,date:todayISO(),done:false}); toast('Sales task added');} else {data.inbox.push({id:uid(),text:v,date:todayISO()}); toast('Captured to inbox');} $('#quickInput').value=''; save();}
init();
