const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));
const uid = () => Math.random().toString(36).slice(2,9);
const localISO = (date = new Date()) => { const d = new Date(date.getTime() - date.getTimezoneOffset()*60000); return d.toISOString().slice(0,10); };
const todayISO = () => localISO();
const money = n => '£' + Number(n||0).toLocaleString('en-GB', {maximumFractionDigits:2});
const storeKey = 'commandCentrePersonalOS.v2';
const oldKeys = ['commandCentrePersonalOS.v1'];
const defaultTeam = [{id:'marie-hendy', name:'Marie Hendy', role:'Customer Service', color:'#f97316', notes:[], feedback:[], expenses:[]}];
const blank = {tasks:[], contacts:[], deals:[], tickets:[], team:defaultTeam, events:[], expenses:[], logs:[], notes:[], settings:{theme:'dark', monthlyBudget:0}};
let data = JSON.parse(localStorage.getItem(storeKey) || oldKeys.map(k=>localStorage.getItem(k)).find(Boolean) || JSON.stringify(blank));
data = {...blank, ...data, settings:{...blank.settings,...(data.settings||{})}, team:(data.team&&data.team.length?data.team:defaultTeam)};
data.contacts = (data.contacts||[]).map(c=>({favorite:false, ...c}));
data.team = (data.team||[]).map((m,i)=>({color:['#f97316','#22c55e','#38bdf8','#a78bfa','#f43f5e'][i%5], notes:[], feedback:[], expenses:[], ...m}));
let route = location.hash?.replace('#','') || 'dashboard';
let calDate = new Date();
const navItems = [
 ['dashboard','🏠 Command'],['calendar','📅 Calendar'],['tasks','✅ Tasks'],['contacts','👥 Contacts'],['favorites','⭐ Favourites'],['pipeline','💼 Pipeline'],['service','🎧 Service Ops'],['team','🧑‍💼 Team'],['expenses','💷 Expenses'],['dailylog','📝 Daily Log'],['reports','📊 Reports'],['settings','⚙️ Settings']
];
function save(noRender=false){data.settings={...blank.settings,...(data.settings||{})}; localStorage.setItem(storeKey, JSON.stringify(data)); if(!noRender) render();}
function setRoute(r){route=r; if(location.hash.replace('#','')!==r) location.hash=r; render();}
function toast(msg){const t=$('#toast'); if(!t) return; t.textContent=msg; t.classList.remove('hidden'); setTimeout(()=>t.classList.add('hidden'),2200)}
function init(){document.body.classList.toggle('light', data.settings.theme==='light'); $('#todayText').textContent = new Date().toLocaleDateString('en-GB',{weekday:'long', day:'numeric', month:'long', year:'numeric'}); $('#quickAddBtn').onclick=quickAdd; $('#quickInput').addEventListener('keydown',e=>{if(e.key==='Enter')quickAdd()}); $('#clearData').onclick=()=>{ if(confirm('Clear all data from this device?')){data=JSON.parse(JSON.stringify(blank)); save();}}; $('#closeModal').onclick=closeModal; $('#themeBtn').onclick=()=>actions.themeToggle(); $('#commandBtn').onclick=()=>actions.commandPalette(); render();}
function openModal(html){$('#modalContent').innerHTML=html; $('#modal').classList.remove('hidden'); bind();}
function closeModal(){ $('#modal').classList.add('hidden'); $('#modalContent').innerHTML=''; }
function pageTitle(){return navItems.find(x=>x[0]===route)?.[1].replace(/^\S+\s/,'')||'Dashboard'}
window.addEventListener('hashchange',()=>{ const r=location.hash.replace('#','')||'dashboard'; if(navItems.some(x=>x[0]===r)){ route=r; render(); }});
function render(){ $('#pageTitle').textContent = pageTitle(); $('#nav').innerHTML = navItems.map(([id,label])=>`<button class="navbtn ${route===id?'active':''}" onclick="setRoute('${id}')"><span>${label}</span><span>›</span></button>`).join(''); const views={dashboard,calendar,tasks,contacts,favorites,pipeline,service,team,expenses,dailylog,reports,settings}; $('#view').innerHTML = `<div class="view-enter">${views[route]()}</div>`; bind();}
function bind(){ $$('[data-action]').forEach(btn=>btn.onclick=()=>actions[btn.dataset.action]?.(btn.dataset)); $$('.drop').forEach(lane=>{lane.ondragover=e=>e.preventDefault(); lane.ondrop=e=>{const [type,id]=e.dataTransfer.getData('text').split(':'); if(type==='deal'){data.deals.find(x=>x.id===id).stage=lane.dataset.stage} if(type==='ticket'){data.tickets.find(x=>x.id===id).status=lane.dataset.stage} save();};}); $$('.drag').forEach(el=>{el.draggable=true; el.ondragstart=e=>e.dataTransfer.setData('text', el.dataset.drag);});}
function stats(){ const today=todayISO(); const month=today.slice(0,7); return {tasks:data.tasks.filter(t=>!t.done).length, done:data.tasks.filter(t=>t.done && t.date===today).length, pipeline:data.deals.reduce((a,d)=>a+Number(d.value||0),0), weighted:data.deals.reduce((a,d)=>a+Number(d.value||0)*(Number(d.prob||0)/100),0), tickets:data.tickets.filter(t=>t.status!=='Resolved').length, escalated:data.tickets.filter(t=>t.priority==='High' && t.status!=='Resolved').length, meetings:data.events.filter(e=>e.date===today).length, expenses:data.expenses.filter(e=>e.date?.startsWith(month)).reduce((a,e)=>a+Number(e.amount||0),0), faves:data.contacts.filter(c=>c.favorite).length} }
function nextActions(){ let a=[]; const now=todayISO(); data.events.filter(e=>e.date===now).slice(0,3).forEach(e=>a.push(['📅 Calendar',e.title,e.teamId?`Assigned to ${teamName(e.teamId)}`:(e.time||'Today'),'calendar'])); data.tickets.filter(t=>t.priority==='High'&&t.status!=='Resolved').slice(0,3).forEach(t=>a.push(['🚨 Service',t.title,'Escalated / urgent','service'])); data.deals.filter(d=>d.stage!=='Won'&&d.stage!=='Lost'&&(!d.next || d.next<=now)).slice(0,4).forEach(d=>a.push(['💼 Sales',d.name,'Follow-up due','pipeline'])); data.tasks.filter(t=>!t.done && (!t.date || t.date<=now)).slice(0,5).forEach(t=>a.push(['✅ Task',t.title, t.date||'No date','tasks'])); const budget=Number(data.settings?.monthlyBudget||0); const spent=stats().expenses; if(budget && spent>budget) a.unshift(['💷 Expense','Monthly budget exceeded',`${money(spent)} spent vs ${money(budget)} budget`,'expenses']); return a.slice(0,8); }
function dashboard(){ const s=stats(), a=nextActions(), budget=Number(data.settings?.monthlyBudget||0), budgetPct=budget?Math.min(100,Math.round((s.expenses/budget)*100)):0; const focus=a[0]; return `<div class="hero rainbow"><span class="pill pulse">✨ Live Command Centre</span><h2>${focus?focus[1]:'Your day is clear'}</h2><p class="muted">${focus?`${focus[0]} · ${focus[2]}`:'Add tasks, meetings, team leave, expenses, contacts and tickets. Your dashboard will colour-code the day for you.'}</p><div class="actions"><button data-action="commandPalette">⚡ Quick Command</button><button class="ghost" data-action="eventForm">📅 Add Calendar Event</button><button class="ghost" data-action="expenseForm">💷 Add Expense</button></div></div>
 <div class="grid cols-5">${metric('📅 Today',s.meetings,'calendar events','calendar')}${metric('⭐ Favourites',s.faves,'key contacts','favorites')}${metric('💼 Pipeline',money(s.weighted),'weighted forecast','pipeline')}${metric('🎧 Service',s.tickets,'open tickets','service')}${metric('💷 Spend',money(s.expenses),budget?`${budgetPct}% of budget`:'this month','expenses')}</div>
 <div class="grid cols-2" style="margin-top:16px"><div class="card colour-card"><div class="calendar-head"><h3>Next Best Actions</h3><span class="pill">auto-ranked</span></div><div class="list" style="margin-top:12px">${a.length?a.map((x,i)=>`<div class="item priority-item ${i===0?'urgent':i===1?'warn':''}"><div><span class="pill">${x[0]}</span><h3>${x[1]}</h3><p class="muted">${x[2]}</p></div><button class="ghost" onclick="setRoute('${x[3]}')">Open</button></div>`).join(''):'<div class="empty">No priorities yet. Use Quick Add to start building your autopilot.</div>'}</div></div><div class="card teal-card"><div class="calendar-head"><h3>Today Timeline</h3><button class="ghost" data-action="eventForm">+</button></div><div class="list" style="margin-top:12px">${timeline(todayISO())}</div></div></div>
 <div class="grid cols-3" style="margin-top:16px"><div class="card purple-card"><h3>Team Colours</h3><div class="chip-list">${data.team.map(m=>`<span class="team-chip" style="--member:${m.color}">${avatar(m.name)} ${m.name}</span>`).join('')}</div><button class="ghost" data-action="teamForm">Add Team Member</button></div><div class="card blue-card"><h3>Expense Pulse</h3>${categoryBars(['Fuel','Car Hire','Hotels','Food','Misc'])}<div class="actions"><button class="ghost" data-action="expenseForm">Add Expense</button><button class="ghost" data-action="budgetForm">Budget</button></div></div><div class="card pink-card"><h3>7-Day Activity</h3>${heatmap()}<div class="sparkline">${lastDays(7).map((d,i)=>`<i style="height:${Math.max(8,activityScore(d)*16)}px;animation-delay:${i*.04}s"></i>`).join('')}</div></div></div>`}
function metric(label,value,sub,routeName){return `<div class="card stat metric-card" onclick="setRoute('${routeName}')"><span class="pill">${label}</span><strong>${value}</strong><p class="muted">${sub}</p></div>`}
function teamName(id){return data.team.find(m=>m.id===id)?.name||''}
function teamColor(id){return data.team.find(m=>m.id===id)?.color||'#7c3aed'}
function avatar(name='?'){return `<span class="avatar">${name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</span>`}
function categoryBars(cats){const max=Math.max(1,...cats.map(sumCat));return `<div class="mini-bars">${cats.map(c=>`<div class="mini-bar"><span>${catIcon(c)} ${c}</span><span><i style="width:${(sumCat(c)/max)*100}%"></i></span><b>${money(sumCat(c))}</b></div>`).join('')}</div>`}
function catIcon(c){return {'Fuel':'⛽','Car Hire':'🚗','Hotels':'🏨','Food':'🍽️','Misc':'✨'}[c]||'💷'}
function sumCat(c){const month=todayISO().slice(0,7);return data.expenses.filter(e=>e.category===c && e.date?.startsWith(month)).reduce((a,e)=>a+Number(e.amount||0),0)}
function lastDays(n){return Array.from({length:n},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(n-1-i));return localISO(d)})}
function activityScore(d){return data.events.filter(e=>e.date===d).length+data.tasks.filter(t=>t.date===d).length+data.expenses.filter(e=>e.date===d).length+data.logs.filter(l=>l.date===d).length}
function heatmap(){return `<div class="heatmap">${lastDays(14).map(d=>`<div class="heat ${activityScore(d)?'active':''}" title="${d}: ${activityScore(d)} items">${new Date(d).getDate()}</div>`).join('')}</div>`}
function timeline(date){ let rows=[]; data.events.filter(e=>e.date===date).forEach(e=>rows.push([e.time||'All day',e.title,e.type||'Calendar',e.teamId])); data.tasks.filter(t=>t.date===date&&!t.done).forEach(t=>rows.push(['Task',t.title,'To do'])); data.expenses.filter(e=>e.date===date).forEach(e=>rows.push(['Expense',`${e.category} ${money(e.amount)}`,'Spend'])); return rows.length?rows.map(r=>`<div class="item"><div><b>${r[0]}</b><p>${r[1]}</p></div><span class="pill" ${r[3]?`style="border-color:${teamColor(r[3])};color:${teamColor(r[3])}"`:''}>${r[2]}</span></div>`).join(''):'<div class="empty">Nothing scheduled yet.</div>'}
function calendar(){ const y=calDate.getFullYear(), m=calDate.getMonth(); const first=new Date(y,m,1), start=(first.getDay()+6)%7, days=new Date(y,m+1,0).getDate(); let cells=[]; for(let i=0;i<start;i++) cells.push('<div></div>'); for(let d=1;d<=days;d++){const iso=localISO(new Date(y,m,d)); const ev=data.events.filter(e=>e.date===iso); const isToday=iso===todayISO(); cells.push(`<div class="day ${isToday?'today':''}" data-action="eventForm" data-date="${iso}"><div class="date-num">${d}</div>${ev.slice(0,5).map(e=>`<span class="event-chip ${e.type==='Annual Leave'?'leave':''}" style="--event:${teamColor(e.teamId)}">${e.time||''} ${e.type==='Annual Leave'?'🌴 ':''}${e.title}</span>`).join('')}</div>`)} return `<div class="calendar-head"><div><h3>${calDate.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h3><p class="muted">Click any date to add meetings, events or team annual leave.</p></div><div class="actions"><button class="ghost" data-action="prevMonth">‹</button><button class="ghost" data-action="todayMonth">Today</button><button class="ghost" data-action="nextMonth">›</button><button data-action="eventForm">Add Event</button></div></div><div class="team-legend">${data.team.map(m=>`<span style="--member:${m.color}">${avatar(m.name)} ${m.name}</span>`).join('')}</div><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="day-name">${d}</div>`).join('')}${cells.join('')}</div>`}
function tasks(){return `<div class="page-head"><h3>Tasks</h3><button data-action="taskForm">Add Task</button></div>${data.tasks.length?`<div class="list">${data.tasks.map(t=>`<div class="item"><label><input type="checkbox" ${t.done?'checked':''} onchange="actions.toggleTask('${t.id}')"> ${t.title}</label><span class="pill">${t.date||'No date'}</span></div>`).join('')}</div>`:'<div class="empty">No tasks yet.</div>'}`}
function contacts(list=data.contacts){return `<div class="page-head"><div><h3>Contacts</h3><p class="muted">Star your most important people to add them to the Favourites page.</p></div><button data-action="contactForm">Add Contact</button></div>${list.length?`<div class="grid cols-3">${list.map(c=>contactCard(c)).join('')}</div>`:'<div class="empty">No contacts yet.</div>'}`}
function favorites(){return `<div class="page-head"><div><h3>⭐ Favourite Contacts</h3><p class="muted">Your mini page for key contacts only.</p></div><button data-action="contactForm">Add Contact</button></div>${contacts(data.contacts.filter(c=>c.favorite)).replace('<div class="page-head"><div><h3>Contacts</h3><p class="muted">Star your most important people to add them to the Favourites page.</p></div><button data-action="contactForm">Add Contact</button></div>','')}`}
function contactCard(c){return `<div class="card contact-card"><div class="contact-top"><div>${avatar(c.name)}<h3>${c.name}</h3><p class="muted">${c.company||''}</p></div><button class="star ${c.favorite?'on':''}" data-action="toggleFavorite" data-id="${c.id}">${c.favorite?'★':'☆'}</button></div><p>${c.email||''}</p><p>${c.phone||''}</p><div class="actions"><button class="ghost" data-action="contactForm" data-id="${c.id}">Edit</button><button class="ghost" data-action="taskForm" data-title="Follow up with ${c.name}">Follow-up</button></div></div>`}
function pipeline(){const stages=['Lead','Qualified','Proposal','Won']; return `<div class="page-head"><h3>Pipeline</h3><button data-action="dealForm">Add Deal</button></div><div class="kanban">${stages.map(st=>`<div class="lane drop" data-stage="${st}"><h3>${st}<span>${data.deals.filter(d=>d.stage===st).length}</span></h3>${data.deals.filter(d=>d.stage===st).map(d=>`<div class="item drag" data-drag="deal:${d.id}"><div><b>${d.name}</b><p class="muted">${money(d.value)} · ${d.prob||0}%</p></div></div>`).join('')}</div>`).join('')}</div>`}
function service(){const statuses=['New','In Progress','Waiting','Resolved']; return `<div class="page-head"><h3>Service Ops</h3><button data-action="ticketForm">New Ticket</button></div><div class="kanban">${statuses.map(st=>`<div class="lane drop" data-stage="${st}"><h3>${st}<span>${data.tickets.filter(t=>t.status===st).length}</span></h3>${data.tickets.filter(t=>t.status===st).map(t=>`<div class="item drag" data-drag="ticket:${t.id}"><div><b>${t.title}</b><p class="muted">${t.priority||'Normal'} priority</p></div></div>`).join('')}</div>`).join('')}</div>`}
function team(){return `<div class="page-head"><div><h3>Team</h3><p class="muted">Click a team member to add notes, feedback and expenses.</p></div><button data-action="teamForm">Add Team Member</button></div><div class="grid cols-3">${data.team.map(m=>`<div class="card team-card" style="--member:${m.color}" data-action="teamDetail" data-id="${m.id}"><div class="member-banner"></div>${avatar(m.name)}<h3>${m.name}</h3><p class="muted">${m.role||'Team member'}</p><div class="grid tiny"><span class="pill">📝 ${m.notes?.length||0} notes</span><span class="pill">💬 ${m.feedback?.length||0} feedback</span><span class="pill">💷 ${money((m.expenses||[]).reduce((a,e)=>a+Number(e.amount||0),0))}</span></div></div>`).join('')}</div>`}
function expenses(){return `<div class="page-head"><h3>Expenses</h3><div class="actions"><button data-action="expenseForm">Add Expense</button><button class="ghost" data-action="exportExpenses">Export CSV</button></div></div><div class="grid cols-2"><div class="card"><h3>By Category</h3>${categoryBars(['Fuel','Car Hire','Hotels','Food','Misc'])}</div><div class="card"><h3>Recent</h3><div class="list">${data.expenses.slice(-8).reverse().map(e=>`<div class="item"><div><b>${catIcon(e.category)} ${e.category}</b><p class="muted">${e.date} ${e.teamId?'· '+teamName(e.teamId):''} · ${e.note||''}</p></div><strong>${money(e.amount)}</strong></div>`).join('')||'<div class="empty">No expenses yet.</div>'}</div></div></div>`}
function dailylog(){return `<div class="page-head"><h3>Daily Log</h3><button data-action="logForm">Add Structured Log</button></div><div class="list">${data.logs.slice().reverse().map(l=>`<div class="card"><span class="pill">${l.date}</span><h3>Wins</h3><p>${l.wins||'-'}</p><h3>Issues</h3><p>${l.issues||'-'}</p><h3>Ideas</h3><p>${l.ideas||'-'}</p></div>`).join('')||'<div class="empty">No daily logs yet.</div>'}</div>`}
function reports(){const s=stats();return `<div class="grid cols-4">${metric('Tasks',s.tasks,'open','tasks')}${metric('Contacts',data.contacts.length,'total','contacts')}${metric('Team',data.team.length,'members','team')}${metric('Expenses',money(s.expenses),'this month','expenses')}</div><div class="card" style="margin-top:16px"><h3>Expense Export</h3><p class="muted">Export your expense report whenever you need it.</p><button data-action="exportExpenses">Export CSV</button></div>`}
function settings(){return `<div class="grid cols-2"><div class="card"><h3>Theme</h3><p class="muted">Switch between dark and light mode.</p><button data-action="themeToggle">Toggle Theme</button></div><div class="card"><h3>Monthly Budget</h3><p class="muted">Current: ${money(data.settings.monthlyBudget)}</p><button data-action="budgetForm">Set Budget</button></div></div>`}
const options=(arr,val='')=>arr.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('');
const teamOptions=id=>`<option value="">None / Personal</option>${data.team.map(m=>`<option value="${m.id}" ${m.id===id?'selected':''}>${m.name}</option>`).join('')}`;
const actions={
 themeToggle(){data.settings.theme=data.settings.theme==='dark'?'light':'dark'; document.body.classList.toggle('light', data.settings.theme==='light'); save();},
 prevMonth(){calDate.setMonth(calDate.getMonth()-1); render()}, nextMonth(){calDate.setMonth(calDate.getMonth()+1); render()}, todayMonth(){calDate=new Date(); render()},
 toggleTask(id){data.tasks.find(t=>t.id===id).done=!data.tasks.find(t=>t.id===id).done; save()},
 toggleFavorite({id}){const c=data.contacts.find(x=>x.id===id); c.favorite=!c.favorite; save(); toast(c.favorite?'Added to favourites':'Removed from favourites')},
 taskForm(ds={}){openModal(`<h2>Add Task</h2><div class="form"><input id="f_title" placeholder="Task" value="${ds.title||''}"><input id="f_date" type="date" value="${todayISO()}"><button onclick="actions.saveTask()">Save Task</button></div>`)}, saveTask(){data.tasks.push({id:uid(),title:$('#f_title').value,date:$('#f_date').value,done:false}); closeModal(); save()},
 contactForm(ds={}){const c=data.contacts.find(x=>x.id===ds.id)||{}; openModal(`<h2>${c.id?'Edit':'Add'} Contact</h2><div class="form"><input id="f_name" placeholder="Name" value="${c.name||''}"><input id="f_company" placeholder="Company" value="${c.company||''}"><input id="f_email" placeholder="Email" value="${c.email||''}"><input id="f_phone" placeholder="Phone" value="${c.phone||''}"><label class="check"><input id="f_fav" type="checkbox" ${c.favorite?'checked':''}> Favourite contact</label><button onclick="actions.saveContact('${c.id||''}')">Save Contact</button></div>`)}, saveContact(id){const obj={id:id||uid(),name:$('#f_name').value,company:$('#f_company').value,email:$('#f_email').value,phone:$('#f_phone').value,favorite:$('#f_fav').checked}; if(id){Object.assign(data.contacts.find(x=>x.id===id),obj)}else data.contacts.push(obj); closeModal(); save()},
 dealForm(){openModal(`<h2>Add Deal</h2><div class="form"><input id="f_name" placeholder="Deal name"><input id="f_value" type="number" placeholder="Value"><input id="f_prob" type="number" placeholder="Probability %"><select id="f_stage">${options(['Lead','Qualified','Proposal','Won'])}</select><input id="f_next" type="date" value="${todayISO()}"><button onclick="actions.saveDeal()">Save Deal</button></div>`)}, saveDeal(){data.deals.push({id:uid(),name:$('#f_name').value,value:$('#f_value').value,prob:$('#f_prob').value,stage:$('#f_stage').value,next:$('#f_next').value}); closeModal(); save()},
 ticketForm(){openModal(`<h2>New Ticket</h2><div class="form"><input id="f_title" placeholder="Issue / ticket title"><select id="f_priority">${options(['Normal','High'])}</select><select id="f_status">${options(['New','In Progress','Waiting','Resolved'])}</select><button onclick="actions.saveTicket()">Save Ticket</button></div>`)}, saveTicket(){data.tickets.push({id:uid(),title:$('#f_title').value,priority:$('#f_priority').value,status:$('#f_status').value}); closeModal(); save()},
 eventForm(ds={}){openModal(`<h2>Add Calendar Event</h2><div class="form"><div class="form-row"><input id="f_date" type="date" value="${ds.date||todayISO()}"><input id="f_time" type="time"></div><input id="f_title" placeholder="Meeting, event, annual leave..."><div class="form-row"><select id="f_type">${options(['Meeting','Sales','Service','Personal','Annual Leave'])}</select><select id="f_team">${teamOptions('')}</select></div><textarea id="f_note" placeholder="Notes"></textarea><button onclick="actions.saveEvent()">Save Event</button></div>`)}, saveEvent(){data.events.push({id:uid(),date:$('#f_date').value,time:$('#f_time').value,title:$('#f_title').value,type:$('#f_type').value,teamId:$('#f_team').value,note:$('#f_note').value}); closeModal(); save()},
 expenseForm(ds={}){openModal(`<h2>Add Expense</h2><div class="form"><div class="form-row"><input id="f_date" type="date" value="${todayISO()}"><input id="f_amount" type="number" placeholder="Amount"></div><select id="f_cat">${options(['Fuel','Car Hire','Hotels','Food','Misc'])}</select><select id="f_team">${teamOptions(ds.teamId||'')}</select><input id="f_note" placeholder="Notes / receipt reference"><button onclick="actions.saveExpense()">Save Expense</button></div>`)}, saveExpense(){const e={id:uid(),date:$('#f_date').value,amount:$('#f_amount').value,category:$('#f_cat').value,teamId:$('#f_team').value,note:$('#f_note').value}; data.expenses.push(e); if(e.teamId){data.team.find(m=>m.id===e.teamId).expenses.push(e)} closeModal(); save()},
 teamForm(){openModal(`<h2>Add Team Member</h2><div class="form"><input id="f_name" placeholder="Name"><input id="f_role" placeholder="Role"><input id="f_color" type="color" value="#38bdf8"><button onclick="actions.saveTeam()">Save Team Member</button></div>`)}, saveTeam(){data.team.push({id:uid(),name:$('#f_name').value,role:$('#f_role').value,color:$('#f_color').value,notes:[],feedback:[],expenses:[]}); closeModal(); save()},
 teamDetail({id}){const m=data.team.find(x=>x.id===id); openModal(`<div class="team-detail" style="--member:${m.color}"><div class="member-banner"></div>${avatar(m.name)}<h2>${m.name}</h2><p class="muted">${m.role||''}</p><div class="actions"><button onclick="actions.addTeamNote('${id}')">Add Note</button><button onclick="actions.addTeamFeedback('${id}')">Add Feedback</button><button onclick="actions.expenseForm({teamId:'${id}'})">Add Expense</button><button class="ghost" onclick="actions.eventForm({})">Add Calendar Event</button></div><div class="grid cols-3"><div class="card"><h3>Notes</h3>${(m.notes||[]).map(n=>`<p class="note">${n.date}: ${n.text}</p>`).join('')||'<p class="muted">No notes yet.</p>'}</div><div class="card"><h3>Feedback</h3>${(m.feedback||[]).map(n=>`<p class="note">${n.date}: ${n.text}</p>`).join('')||'<p class="muted">No feedback yet.</p>'}</div><div class="card"><h3>Expenses</h3>${(m.expenses||[]).map(e=>`<p class="note">${e.date}: ${catIcon(e.category)} ${e.category} ${money(e.amount)}</p>`).join('')||'<p class="muted">No expenses yet.</p>'}</div></div></div>`)},
 addTeamNote(id){const text=prompt('Add note'); if(text){data.team.find(m=>m.id===id).notes.push({date:todayISO(),text}); save(true); actions.teamDetail({id});}}, addTeamFeedback(id){const text=prompt('Add feedback'); if(text){data.team.find(m=>m.id===id).feedback.push({date:todayISO(),text}); save(true); actions.teamDetail({id});}},
 logForm(){openModal(`<h2>Structured Daily Log</h2><div class="form"><input id="f_date" type="date" value="${todayISO()}"><textarea id="f_wins" placeholder="Wins"></textarea><textarea id="f_issues" placeholder="Issues"></textarea><textarea id="f_ideas" placeholder="Ideas"></textarea><button onclick="actions.saveLog()">Save Log</button></div>`)}, saveLog(){data.logs.push({id:uid(),date:$('#f_date').value,wins:$('#f_wins').value,issues:$('#f_issues').value,ideas:$('#f_ideas').value}); closeModal(); save()},
 budgetForm(){openModal(`<h2>Monthly Budget</h2><div class="form"><input id="f_budget" type="number" value="${data.settings.monthlyBudget||0}"><button onclick="actions.saveBudget()">Save Budget</button></div>`)}, saveBudget(){data.settings.monthlyBudget=$('#f_budget').value; closeModal(); save()},
 commandPalette(){openModal(`<h2>Quick Command</h2><p class="muted">Jump straight to your most-used actions.</p><div class="command-grid"><button onclick="actions.eventForm();">📅 Add meeting / leave</button><button onclick="actions.expenseForm();">💷 Add expense</button><button onclick="actions.contactForm();">👥 Add contact</button><button onclick="actions.teamForm();">🧑‍💼 Add team member</button><button onclick="actions.ticketForm();">🎧 New ticket</button><button onclick="actions.logForm();">📝 Daily log</button></div>`)},
 exportExpenses(){const rows=[['Date','Category','Amount','Team Member','Note'],...data.expenses.map(e=>[e.date,e.category,e.amount,teamName(e.teamId),e.note])]; const csv=rows.map(r=>r.map(v=>`"${String(v||'').replaceAll('"','""')}"`).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download='command-centre-expenses.csv'; a.click();},
};
function quickAdd(){const v=$('#quickInput').value.trim(); if(!v)return; const low=v.toLowerCase(); const amt=(v.match(/£?([0-9]+(?:\.[0-9]{1,2})?)/)||[])[1]; if(low.includes('fuel')||low.includes('hotel')||low.includes('car hire')||low.includes('expense')){data.expenses.push({id:uid(),date:todayISO(),amount:amt||0,category:low.includes('fuel')?'Fuel':low.includes('hotel')?'Hotels':low.includes('car hire')?'Car Hire':'Misc',note:v,teamId:''}); toast('Expense added');} else if(low.includes('meeting')||low.includes('annual leave')||low.includes('leave')){data.events.push({id:uid(),date:todayISO(),time:'',title:v,type:low.includes('leave')?'Annual Leave':'Meeting',teamId:'',note:''}); toast('Calendar event added');} else {data.tasks.push({id:uid(),title:v,date:todayISO(),done:false}); toast('Task added');} $('#quickInput').value=''; save();}
init();
